// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knypbtvagnjaqtptfinn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtueXBidHZhZ25qYXF0cHRmaW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzc2MTYsImV4cCI6MjA2ODcxMzYxNn0.OoANH5qBw6O9BJfTWaYdETIOpft9or7lJ2ejcPrqyl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});